source 'http://rubygems.org'

gem 'nesta', '<%= Nesta::VERSION %>'
<% if @options['vlad'] %>gem 'vlad', '2.1.0'
gem 'vlad-git', '2.2.0'<% end %>

group :development do
  gem 'mr-sparkle'
end

# gem 'debugger'
