source 'https://rubygems.org'

gem 'nesta', '<%= Nesta::VERSION %>'
gem 'redcarpet'
<% if @options['vlad'] %>gem 'vlad', '2.1.0'
gem 'vlad-git', '2.2.0'<% end %>

group :development do
  gem 'shotgun'
end

# gem (RUBY_VERSION =~ /^1.9/) ? 'ruby-debug19': 'ruby-debug'
